version: 2

sources:
  - name: kpetrynka
    database: econ250-2025  
    schema: kpetrynka  
    tables:
      - name: week3_arxiv
      - name: sheet_external
  
  - name: test_dataset
    database: econ250-2025  
    schema: test_dataset  
    tables:
      - name: air_raid_alerts_ua
        loaded_at_field: started_at
        freshness:
          error_after:
            period: day
      - name: week3_arxiv
      - name: sheet_external
      - name: week5_web_transactions
        columns:
          - name: transaction.transactionId
            data_tests:
            - not_null:
                config:
                  severity: error
                  error_if: ">10"
                  warn_if: ">0"
          - name: visitId
            description: '{{ doc("visitid_description") }}'
      - name: week5_web_visits
        columns: 
          - name: visitId
            description: '{{ doc("visitid_description") }}'
      - name: week5_hits
        columns:
          - name: visitId
            description: '{{ doc("visitid_description") }}'


  - name: google_trends
    database: bigquery-public-data
    schema: google_trends  
    tables:
      - name: international_top_terms
        loaded_at_field: TIMESTAMP(refresh_date)
        freshness:
          filter: "refresh_date >= current_date() - 7"
          error_after:
            count: 2
            period: day
